# opt-in to Travis new infrastructure
sudo: false

language: ruby
rvm:
  - 2.2

# for faster builds
cache: bundler
env: BUNDLE_PATH=bundle-vendor/bundle

# we must override install, or Travis's default Gemfile support
# will kick in and use `vendor`, ignoring our BUNDLE_PATH
# declaration in `.bundle/config`
install:
- bundle install

script:
- bundle exec jekyll build 2> error.log
- cat >&2 error.log
- ( ! grep -qie Error -e Warn error.log )
- find ./_site \( -type d \( -name events -o -name training \) -prune -false \) -o \( -type f ! -name error.log -empty \)
- find ./_site \( -type d \( -name events -o -name training \) -prune -false \) -o \( -type f ! -name error.log -empty \) | ( ! read )
