title: The Scala Programming Language

scalaversion: "2.12.2"

baseurl: ""
markdown: kramdown
exclude:
  - bundle-vendor/
  - blog/README.md
  - training/README.md
  - README.md
  - news/README.md
  - events/README.md
  - Gemfile
  - Gemfile.lock
future: true
