title: The Scala Programming Language

scalaversion: "2.11.2"
devscalaversion: 2.11.2"
# scala_maindownload_unix: "/files/archive/scala-2.11.2.tgz"
# scala_maindownload_windows: "/files/archive/scala-2.11.2.msi"
baseurl: ""
