title: The Scala Programming Language

scalaversion: "2.13.2"

url: https://www.scala-lang.org
baseurl: ""
markdown: kramdown
highlighter:

exclude:
  - bundle-vendor/
  - bin/
  - blog/README.md
  - training/README.md
  - README.md
  - news/README.md
  - events/README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - Procfile
  - Rakefile

future: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: blog-detail
      includeTOC: true

#Â Custom collections
collections:
  scala_items:
    output: false
  online_courses:
    output: false
  trainings:
    output: false
  events:
    output: false
  contribute_resources:
    output: false
  books:
    output: false
  downloads:
    output: true
  posts:
    output: true

# Pagination
pagination:
  limit: false
  per_page: 5
  title_suffix: " - :num"
  permalink: /:num/

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

sass:
  style: compressed
